esi_lecture_client/esi_lecture_client/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('odoo_connexion.urls')),
    path('book/', include('odoo_book.urls')),
]

esi_lecture_client/odoo_book/urls.py
from django.urls import path
from . import views
from .views import BookView

app_name = 'odoo_book'
urlpatterns = [
    path('', BookView.index, name="index"),
    path('addLike/<int:book_id>', BookView.addLike, name="addLike"),
    ]

esi_lecture_client/odoo_connexion/urls.py
from django.urls import path
from . import views
from .views import IndexView, FormView

app_name = 'odoo_connexion'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('loginForm', FormView.as_view(), name='loginForm'),
    path('login', views.connect, name="login")
    ]

esi_lecture_client/odoo_book/models.py
from django.db import models

# Create your models here.

esi_lecture_client/odoo_connexion/models.py
from django.db import models


# Create your models here.

class User(models.Model):
    login = models.CharField("login", max_length=200)
    password = models.CharField("password", max_length=200)

    class Meta:
        constraints = [
            models.UniqueConstraint('login', name='unique_login')
        ]

esi_lecture_client/odoo_connexion/forms.py
from django import forms

from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'login',
            'password'
        ]




        

esi_lecture_client/odoo_book/views.py
import xmlrpc.client

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.conf import settings
import xml_rpc


class BookView:
    uid = False
    context = {}
    password = ''

    @staticmethod
    def index(request):
        try:
            with open(settings.BASE_DIR / '.env') as f:
                login, password = f.readline().split(',')
                BookView.password = password
            BookView.uid = xml_rpc.connect(login, password)
            if not BookView.uid:
                BookView.context = {}
                messages.error(request, "Veuillez vous connecter pour voir vos livres.")

            books = xml_rpc.get_books(BookView.uid, BookView.password)
            search_query = request.GET.get('search', '').lower()

            if search_query:  # Vérifiez si une chaîne de recherche est présente
                filtered_books = [book for book in books if search_query in  book['name'].lower()]
                sorted_books = sorted(filtered_books, key=lambda x: (-x.get('like_count', 0), x.get('name', '').lower()))   
                BookView.context = {'books': sorted_books}
            else:
                filtered_books = books  # Si aucune recherche n'est effectuée, retournez tous les livres 
                BookView.context = {'books': filtered_books} 

        except FileNotFoundError:
            BookView.context = {}
            messages.error(request, "Veuillez d'abord vous connecter.")
        except ConnectionError:
            BookView.context = {}
            messages.error(request, "Assurez-vous que le serveur Odoo est fonctionne")

        return render(request, 'odoo_book/index.html', BookView.context)


    @staticmethod
    def addLike(request, book_id):  
        try:
            xml_rpc.add_like(BookView.uid, BookView.password, book_id)
        except xmlrpc.client.Fault as e:
            BookView.context = {}   
        except FileNotFoundError:
            BookView.context = {}
            messages.error(request, "Veuillez d'abord vous connecter.")
        except ConnectionError:
            BookView.context = {}
            messages.error(request, "Assurez-vous que le serveur Odoo est fonctionne")

        #return render(request, 'odoo_book/index.html', BookView.context)   
        return HttpResponseRedirect(reverse('odoo_book:index'))        

esi_lecture_client/odoo_connexion/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from django.http import HttpResponse

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings


from .forms import UserForm
from .models import User

import xml_rpc as xml_rpc


class IndexView(TemplateView):
    template_name = "odoo_connexion/index.html"

class FormView(ListView):
    model = User
    template_name = "odoo_connexion/loginForm.html"
    context_object_name = "odoo_connexion"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['userForm'] = UserForm
        return context   

def _write_info(login, username):
    with open(settings.BASE_DIR / '.env', 'w') as f:
        f.write(f"{login},{username}")


def connect(request):
    form = UserForm(request.POST)
     # Un Model Form ne sera pas valide si un champ est déjà dans la DB (très ennuyeux)
    # Nous devons essayer avec la clause else pour voir si la connexion à Odoo fonctionne
    # Beaucoup de code à copier ici
    if form.is_valid():
        login, password = form.cleaned_data['login'], form.cleaned_data['password']
        try:
            uid = xml_rpc.connect(login, password)
            if uid:
                User.objects.create(
                    login=login,
                    password=password,
                )
                _write_info(login, password)
                messages.success(request, "Identification réussie !")
            else:
                messages.error(request, "L'identification a échoué.")
        except ConnectionError:
            messages.error(request, "Le serveur Odoo n'est pas démarré !")
    else:
        login, password = form.data['login'], form.data['password']  # data and not cleaned_data
        try:
            uid = xml_rpc.connect(login, password)
            if uid:
                user = User.objects.get(
                    login=login,
                    password=password,
                )
                if user:
                    messages.success(request, "Identification réussie !")
                    _write_info(login, password)
            else:
                messages.error(request, "L'identification a échoué.")
        except ConnectionError:
            messages.error(request, "Le serveur Odoo n'est pas démarré !")
    # redirection vers le site après la requête POST
    # redirection après la gestion correcte pour empêcher de poster deux fois
    return HttpResponseRedirect(reverse('odoo_connexion:loginForm'))        

   

esi_lecture_client/odoo_book/templates/odoo_book/index.html
{% extends "_canvas.html" %}

{% block title %} L'index {% endblock title %}

{% block content %}
        <h2 class="h2"> Vos livres. </h2>
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
              <form class="d-flex" role="search" method="get" action="{% url 'odoo_book:index' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" value="{{ request.GET.search }}">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </nav>
        <div class="mt-5 d-flex flex-wrap" style="display: flex;">

        {% if books %}
            {% for book in books %}
            <div class="card m-8" style="margin-bottom: 10px;" >
                <div class="card-header text-light bg-dark">
                    {{ book.name }}
                </div>
                
                <div class="card-body" >
                    <table>
                        <tbody>
                        <tr>
                            <td><img src="data:image/jpeg;base64,{{ book.cover_image }}" style="width: 100px; height: auto; margin: 5px;"/> </td>
                            <td>
                                <table style="font-size: 20px;">
                                    <tr>
                                        <td> Autheurs : {{ book.authors }} </td>
                                    </tr>
                                    <tr>
                                        <td> Nombre de pages : {{ book.num_pages }}</td>
                                    </tr>
                                    <tr>
                                        <td>Nombre de like : {{ book.like_count }}</td>
                                    </tr>
                                    <tr>
                                        <td> Date de publication : {{ book.publication_date}}</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>    
                        </tbody>
                    </table>
                    <hr>
                    <tr>
                        <td>{{ book.description|safe }}</td>
                    </tr>
                    <form action="{% url 'odoo_book:addLike' book.id %}" method="POST">
                        {% csrf_token %}        
                        <button class="ui button" type="submit" action="{% url 'odoo_book:addLike' book.id %}">
                            {% if book.is_liked_by_current_user %}
                                <i class="thumbs up icon"></i>
                            {% else %}
                                <i class="thumbs up outline icon"></i>
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <div class="container m-5">
            <h4>
                <alert class="alert alert-warning">There are no books!</alert>
            </h4>
        </div>
        {% endif %}    

{% endblock content %}

esi_lecture_client/odoo_connexion/templates/odoo_connexion/index.html
{% extends "_canvas.html" %}

{% block title %} L'index {% endblock title %}

{% block content %}
        <h2 class="h2"> Bienvenu dans la page d'accueil. </h2>


{% endblock content %}

esi_lecture_client/odoo_connexion/templates/odoo_connexion/loginForm.html
{% extends "_canvas.html" %}
{% block title %}Esi Lecture Connection{% endblock %}

{% block content %}
<div class="container m-5">
    <div class="p-5 text-bg-dark rounded-3 d-inline-block">
        <form action="{% url 'odoo_connexion:login' %}" method="POST">
            {% csrf_token %}
                <table >
                    {{ userForm.as_table }}
                </table>
            <button type="submit" class="btn btn-primary mt-5">Connexion</button> 
        </form>
    </div>
{% if messages %}
<ul class="messages mt-5">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }} d-inline-block"{% endif %}>
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <span class="alert alert-success">{{ message }}</span>
    {% endif %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <span class="alert alert-danger">{{ message }}</span>
    {% endif %}

    </li>
    {% endfor %}
</ul>
{% endif %}
</div>
{% endblock %}

esi_lecture_client/templates/_canvas.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 	
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <title>{% block title %}Esi Lecture{% endblock title %}</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Esi Lecture</span>
                    </a>
                    <hr>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a href="{% url 'odoo_connexion:index' %}" class="nav-link align-middle px-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                                    <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
                                </svg>
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline ">Home</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'odoo_connexion:loginForm' %}" class="nav-link px-0 align-middle">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                                  </svg>
                                <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Connexion</span></a>
                        </li>
                        <li>
                            <a href="{% url 'odoo_book:index' %}" class="nav-link px-0 align-middle">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
                                    <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783"/>
                                  </svg>
                                <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Book</span></a>
                        </li>
                    </ul>
                    <hr>
                </div>
            </div>
            <div class="col py-3" >
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>

    
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>	
</body>
</html>